version: '3.6'
services:
  telegraf:
    image: telegraf:latest
    container_name: telegraf
    restart: always
    environment:
      HOSTNAME: telegraf-mac-os
    volumes:
      - ./telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro
    networks:
      grafana_tick_net:
    depends_on:
      - influxdb

  influxdb:
    image: influxdb:1.8
    container_name: influxdb
    restart: always
    environment:
      - INFLUXDB_DB=influx
      - INFLUXDB_ADMIN_USER=admin123
      - INFLUXDB_ADMIN_PASSWORD=admin123
    ports:
      - '8086:8086'
    volumes:
      - influxdb_data:/var/lib/influxdb
      - ./influxdb/influxdb.conf:/etc/influxdb/influxdb.conf:ro
    networks:
      grafana_tick_net:

  grafana:
    image: grafana/grafana
    ports:
      - '3000:3000'
    volumes:
      - grafana_data:/var/lib/grafana
    environment:
      - GF_INSTALL_PLUGINS=grafana-piechart-panel,grafana-worldmap-panel
      - GF_SERVER_ROOT_URL=http://localhost:3000
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    networks:
      grafana_tick_net:
    links:
      - influxdb

  elasticsearch:
    image: elasticsearch:8.7.1
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
    networks:
      grafana_tick_net:

  kibana:
    image: kibana:8.7.1
    container_name: kibana
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
    networks:
      grafana_tick_net:

  chronograf:
    image: chronograf:latest
    ports:
      - '8888:8888'
    volumes:
      - chronograf_data:/var/lib/chronograf
    environment:
      RESOURCES_PATH: /usr/share/chronograf/resources
    networks:
      grafana_tick_net:
    links:
      - influxdb

  logstash:
    image: docker.elastic.co/logstash/logstash:7.12.0
    container_name: logstash
    restart: always
    volumes:
      - logstash_config:/usr/share/logstash/config
      - logstash_pipeline:/usr/share/logstash/pipeline
    ports:
      - "5044:5044"

  kapacitor:
    image: kapacitor:latest
    volumes:
      - kapacitor_data:/var/lib/kapacitor
      - ./kapacitor/kapacitor.conf:/etc/kapacitor/kapacitor.conf
    links:
      - influxdb
    networks:
      grafana_tick_net:

networks:
  grafana_tick_net:

volumes:
  influxdb_data:
  chronograf_data:
  kapacitor_data:
  elasticsearch_data:
  grafana_data:
  logstash_config:
  logstash_pipeline: